apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plataforma-agentes
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - infra.yaml
  - apps.yaml
  - ingress.yaml
  - ollama-model-job.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: frontend-html
    files:
      - index.html=frontend-index.html
  - name: agent-service-code
    files:
      - main.py=agent-service-main.py
  - name: api-gateway-code
    files:
      - main.py=api-gateway-main.py
  - name: llm-gateway-code
    files:
      - main.py=llm-gateway-main.py
