apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: plataforma-agentes
type: Opaque
stringData:
  POSTGRES_USER: agent
  POSTGRES_PASSWORD: agent
  POSTGRES_DB: memory
  DATABASE_URL: postgresql://agent:agent@postgres/memory
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: plataforma-agentes
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
  RABBITMQ_URL: amqp://guest:guest@rabbitmq/
